<a href="https://colab.research.google.com/github/dipayandas97/Spiking-Neural-Network/blob/master/Genetic_algorithm_module.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

class GA:
    def __init__(self):
        pass

    def matrix_to_vector(self, matrices): #returns list(matrix) of vectors for list(matrix) of 3D matrices
        if len(matrices.shape) != 4:
            raise Exception('Input should be 4D matrices (array of 3D matrices)')
        vectors = [m.flatten() for m in matrices]
        return np.asarray(vectors)

    def vector_to_matrix(self, vectors, matrices):
        if len(matrices.shape) != 4:
            raise Exception('Input matrix should be 4D matrices (array of 3D matrices)')
        new_matrices = [v.reshape(matrices.shape[1], matrices.shape[2], matrices.shape[3]) for v in vectors]
        return np.asarray(new_matrices)

    def select_mating_pool(self, population, fitness, num_parents): 
        parents = np.zeros((num_parents, population.shape[1]))
        for idx in range(num_parents):
            max_id = np.where(fitness==np.max(fitness))[0][0]
            parents[idx,:] = population[max_id,:]
            fitness[max_id] = -9999999
        return parents

    def crossover(self, parents, num_offsprings):
        offsprings = np.zeros((num_offsprings, parents.shape[1]))
        crossover_point = np.uint32(parents.shape[1]/2)
        for k in range(num_offsprings):
            parent_1 = k % parents.shape[0]
            parent_2 = (k+1) % parents.shape[0]
            offsprings[k, :crossover_point] = parents[parent_1, :crossover_point]
            offsprings[k, crossover_point:] = parents[parent_2, crossover_point:]
        return offsprings

    def mutate(self, offsprings, mutation_percent):
        num_of_cells_to_mutate = np.uint32((mutation_percent/100) * offsprings.shape[1])
        for idx in range(offsprings.shape[0]):
            mutation_indices = np.random.randint(0, offsprings.shape[1], num_of_cells_to_mutate)
            random_val = np.random.uniform(-1.0,1.0,1)
            offsprings[idx, mutation_indices] += random_val
        return offsprings

In [0]:
g = GA()

In [0]:
m = np.random.randint(1,10,size=(10,3,3,2))

In [203]:
#n = m.reshape(1, m.shape[0], m.shape[1], m.shape[2])
v = g.matrix_to_vector(m)
v

array([[8, 7, 9, 1, 9, 2, 9, 3, 3, 1, 8, 8, 1, 1, 9, 8, 1, 5],
       [8, 8, 9, 3, 1, 2, 3, 4, 3, 3, 7, 4, 2, 9, 1, 6, 9, 1],
       [4, 1, 1, 6, 4, 9, 7, 3, 1, 8, 7, 7, 6, 6, 4, 1, 2, 4],
       [5, 1, 1, 6, 4, 1, 8, 6, 6, 3, 4, 7, 4, 1, 1, 2, 4, 6],
       [5, 6, 3, 8, 5, 8, 1, 5, 8, 5, 8, 8, 6, 4, 3, 9, 2, 7],
       [4, 8, 4, 2, 3, 2, 2, 6, 9, 3, 2, 4, 8, 8, 7, 2, 8, 4],
       [9, 2, 8, 3, 5, 4, 2, 4, 1, 3, 2, 9, 8, 9, 7, 6, 6, 7],
       [1, 7, 6, 2, 8, 3, 8, 1, 8, 8, 7, 9, 4, 8, 5, 3, 8, 8],
       [6, 3, 9, 7, 6, 6, 5, 2, 7, 5, 7, 4, 8, 4, 8, 6, 8, 5],
       [7, 2, 1, 8, 1, 8, 1, 3, 7, 8, 8, 7, 5, 8, 5, 9, 6, 1]])

In [204]:
g.vector_to_matrix(v, m)

array([[[[8, 7],
         [9, 1],
         [9, 2]],

        [[9, 3],
         [3, 1],
         [8, 8]],

        [[1, 1],
         [9, 8],
         [1, 5]]],


       [[[8, 8],
         [9, 3],
         [1, 2]],

        [[3, 4],
         [3, 3],
         [7, 4]],

        [[2, 9],
         [1, 6],
         [9, 1]]],


       [[[4, 1],
         [1, 6],
         [4, 9]],

        [[7, 3],
         [1, 8],
         [7, 7]],

        [[6, 6],
         [4, 1],
         [2, 4]]],


       [[[5, 1],
         [1, 6],
         [4, 1]],

        [[8, 6],
         [6, 3],
         [4, 7]],

        [[4, 1],
         [1, 2],
         [4, 6]]],


       [[[5, 6],
         [3, 8],
         [5, 8]],

        [[1, 5],
         [8, 5],
         [8, 8]],

        [[6, 4],
         [3, 9],
         [2, 7]]],


       [[[4, 8],
         [4, 2],
         [3, 2]],

        [[2, 6],
         [9, 3],
         [2, 4]],

        [[8, 8],
         [7, 2],
         [8, 4]]],


       [[[9, 2],
         [8, 3],


In [205]:
fitness = np.random.randint(0,100, len(v))
parents = g.select_mating_pool(v, fitness, 3)
parents

array([[1., 7., 6., 2., 8., 3., 8., 1., 8., 8., 7., 9., 4., 8., 5., 3.,
        8., 8.],
       [8., 7., 9., 1., 9., 2., 9., 3., 3., 1., 8., 8., 1., 1., 9., 8.,
        1., 5.],
       [7., 2., 1., 8., 1., 8., 1., 3., 7., 8., 8., 7., 5., 8., 5., 9.,
        6., 1.]])

In [211]:
offsprings = g.crossover(parents, 5)
offsprings

array([[1., 7., 6., 2., 8., 3., 8., 1., 8., 1., 8., 8., 1., 1., 9., 8.,
        1., 5.],
       [8., 7., 9., 1., 9., 2., 9., 3., 3., 8., 8., 7., 5., 8., 5., 9.,
        6., 1.],
       [7., 2., 1., 8., 1., 8., 1., 3., 7., 8., 7., 9., 4., 8., 5., 3.,
        8., 8.],
       [1., 7., 6., 2., 8., 3., 8., 1., 8., 1., 8., 8., 1., 1., 9., 8.,
        1., 5.],
       [8., 7., 9., 1., 9., 2., 9., 3., 3., 8., 8., 7., 5., 8., 5., 9.,
        6., 1.]])

In [212]:
g.mutate(offsprings, 20)

array([[1.73371777, 7.        , 6.        , 2.        , 8.        ,
        3.        , 8.        , 1.        , 8.73371777, 1.        ,
        8.        , 8.73371777, 1.        , 1.        , 9.        ,
        8.        , 1.        , 5.        ],
       [8.        , 7.        , 8.4293036 , 1.        , 9.        ,
        2.        , 9.        , 2.4293036 , 3.        , 8.        ,
        8.        , 7.        , 5.        , 8.        , 5.        ,
        9.        , 6.        , 0.4293036 ],
       [7.        , 1.71041719, 1.        , 8.        , 1.        ,
        8.        , 0.71041719, 3.        , 7.        , 8.        ,
        7.        , 9.        , 4.        , 8.        , 5.        ,
        3.        , 7.71041719, 8.        ],
       [1.        , 7.        , 6.        , 1.08889058, 7.08889058,
        3.        , 8.        , 1.        , 8.        , 0.08889058,
        8.        , 8.        , 1.        , 1.        , 9.        ,
        8.        , 1.        , 5.        ],
    